### ISSUE TITLE
请问flex-block如何设置每行随机放置文章的个数以及文章模块的大小

### ISSUE THREAD

**Issue by myc1995** [miiiku/flex-block#4]
您好，请问flex-block如何设置每行随机放置文章的个数以及文章模块的大小！
搞了好久，都没成功！
望尽快翻我牌子！！！
么么哒！！！

**Comment by miiiku** [comment]
**下面这个配置咯就好啦，文章模块的大小是根据文章标题的长度来显示的。**

## 长标题

进入`flex-block`配置文件`_config.yml`找到`large_legnth`

``` yml
# large cover
# long: [article, link]
# short: [category, tag]
large_legnth:
  long: 20
  short: 5
```

**long:** 作用于`文章`和`友链`卡片

**short:** 作用于`分类`和`标签`卡片

设置Card封面的大小，如 `long: 20` 表示如果文章标题长度大于20，文章卡片显示为长文章

*如果启用了友链，则会判断`友链名称`和`友链描述`两个字段长度*
